name: CI Back

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: "mysql://root:root@127.0.0.1:3306/FantasyRealmBDD_test?serverVersion=8.0"

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: FantasyRealmBDD_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl, pdo, pdo_mysql
          coverage: none

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Generate JWT keys
        run: php bin/console lexik:jwt:generate-keypair --skip-if-exists

      - name: Prepare test database
        run: |
          php bin/console doctrine:database:create --env=test --if-not-exists
          php bin/console doctrine:migrations:migrate --env=test --no-interaction

      - name: Run Symfony lint
        run: |
          php bin/console lint:yaml config/
          php bin/console lint:twig templates/
          php bin/console lint:container

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit
